@startuml
left to right direction

actor "Cliente" as Cliente
actor "Sistema BACEN" as BACEN

rectangle "Área do Pix - IFBank" {
    usecase "Autenticar Usuário" as UC1
    usecase "Consultar Saldo" as UC2
    usecase "Cadastrar Chave Pix" as UC3
    usecase "Realizar Pix" as UC4
    usecase "Validar Chave Pix" as UC5
}

Cliente --> UC1
Cliente --> UC2
Cliente --> UC3
Cliente --> UC4

UC2 ..> UC1 : <<include>>
UC3 ..> UC1 : <<include>>
UC4 ..> UC1 : <<include>>
UC4 ..> UC5 : <<include>>

BACEN --> UC5

@enduml
